[package]
name = "Efis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
nom = "7.1.3"
rand = "0.8.3"
thiserror = "1.0.40"
